/*
 * Tanque.java
 */
package net.ausiasmarch.tanque.modelo;

/**
 *
 * @author Administrador
 */
public class Tanque extends javax.swing.JPanel {

    private EstadoTanque estado;

    /**
     * Creates new form Tanque
     */
    public Tanque() {
        initComponents();
        estado = EstadoTanque.VACIO;
        jLabelVacio.setVisible(true);
        jLabelMedio.setVisible(false);
        jLabelLleno.setVisible(false);

    }

    public void llenarMedio() {

        /* if (estado == EstadoTanque.VACIO ){
         estado=EstadoTanque.MEDIO;
         jLabelVacio.setVisible(false);
         jLabelMedio.setVisible(true);
         jLabelLleno.setVisible(false);
         }
         else{
         if (estado == EstadoTanque.MEDIO){
         estado=EstadoTanque.LLENO;
         jLabelVacio.setVisible(false);
         jLabelMedio.setVisible(false);
         jLabelLleno.setVisible(true);   
         }
         }*/
        switch (estado) {
            case VACIO:
                estado = EstadoTanque.MEDIO;
                jLabelVacio.setVisible(false);
                jLabelMedio.setVisible(true);
                jLabelLleno.setVisible(false);
                break;
            case MEDIO:
                estado = EstadoTanque.LLENO;
                jLabelVacio.setVisible(false);
                jLabelMedio.setVisible(false);
                jLabelLleno.setVisible(true);
        }
    }

    public void vaciarMedio() {

        if (estado == EstadoTanque.LLENO) {
            estado = EstadoTanque.MEDIO;
            jLabelVacio.setVisible(false);
            jLabelMedio.setVisible(true);
            jLabelLleno.setVisible(false);

        } else {
            if (estado == EstadoTanque.MEDIO) {
                estado = EstadoTanque.VACIO;
                jLabelVacio.setVisible(true);
                jLabelMedio.setVisible(false);
                jLabelLleno.setVisible(false);
            }
        }
    }

    public EstadoTanque getEstado() {

        return estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLleno = new javax.swing.JLabel();
        jLabelMedio = new javax.swing.JLabel();
        jLabelVacio = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/tanque/img/Lleno.png"))); // NOI18N
        add(jLabelLleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/tanque/img/Medio.png"))); // NOI18N
        add(jLabelMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelVacio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/tanque/img/Vacio.png"))); // NOI18N
        add(jLabelVacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLleno;
    private javax.swing.JLabel jLabelMedio;
    private javax.swing.JLabel jLabelVacio;
    // End of variables declaration//GEN-END:variables
}
